// Package schema compiles a record doc's attribute declarations to JSON
// Schema (DESIGN §4).
//
// The declarations are the contract; this is their machine-readable
// form, and it is generated rather than written for the reason the
// declarations sit inside their rules: a schema authored beside a doc is
// a second statement of the doc, and two statements of one rule drift.
// A consumer — Catapult's gate comparing its loader against
// docs/dsl/chain.md — compiles on every run and never reads a stored
// copy, so there is no copy to go stale.
//
// What a node says is what its declaration says and nothing more. A map
// declaring members is closed (unevaluatedProperties: false), because a
// contract that admits keys refuses the rest; a map declaring `*` takes
// any key with values of that shape instead; a map or list declaring no
// children is unconstrained, since nothing was said about them. Each
// declared node carries `x-rule`, the rule it is declared under, and
// that rule's lead as its description — the join DESIGN §4 builds on,
// so a reader of the schema is one `pipeline reasons` from why a key
// exists.
//
// Draft 2020-12 rather than draft 7, for one keyword: a `when`-gated
// member is defined only inside an if/then, and only
// unevaluatedProperties sees into those. additionalProperties judges a
// key by the `properties` beside it alone, so under it a gated member
// is refused even when its condition holds. Measured on the golden
// schema with python-jsonschema 4.26: a queue entry carrying its own
// gated `flow` validates under unevaluatedProperties and is rejected with
// additionalProperties swapped in.
package schema

import (
	"bytes"
	"encoding/json"
	"fmt"
	"sort"
	"strings"

	"github.com/SwaggerAllen/orchestration/internal/reasons"
)

// Dialect is the JSON Schema draft every compiled schema declares.
const Dialect = "https://json-schema.org/draft/2020-12/schema"

type node struct {
	decl  *reasons.Declaration
	named map[string]*node
	star  *node
	items *node
}

func newNode(d *reasons.Declaration) *node {
	return &node{decl: d, named: map[string]*node{}}
}

// Compile renders a doc's declarations as a JSON Schema whose root is the
// file the doc is a contract for. It refuses with every finding
// reasons.CheckDeclarations reports — the audit's own check, so the two
// cannot disagree about what compiles — and refuses a doc that declares
// nothing, because an empty schema would accept every file and a gate
// comparing against it would pass on nothing.
func Compile(ix reasons.Index) (map[string]any, []string) {
	if problems := reasons.CheckDeclarations(ix); len(problems) > 0 {
		return nil, problems
	}
	if len(ix.Doc.Declarations) == 0 {
		return nil, []string{fmt.Sprintf("%s declares no attributes — there is nothing to compile (DESIGN §4)", ix.Path)}
	}
	// Parents before children. CheckDeclarations has already proven every
	// parent is declared, so a walk by ascending depth always finds one.
	decls := append([]reasons.Declaration(nil), ix.Doc.Declarations...)
	sort.SliceStable(decls, func(i, j int) bool { return len(decls[i].Segs) < len(decls[j].Segs) })
	root := newNode(nil)
	shapes := map[string]*node{}
	for i := range decls {
		d := &decls[i]
		if d.IsShape() {
			shapes[d.Segs[0]] = newNode(d)
			continue
		}
		cur, segs := root, d.Segs
		if strings.HasPrefix(segs[0], "$") {
			cur, segs = shapes[segs[0]], segs[1:]
		}
		for _, s := range segs[:len(segs)-1] {
			cur = cur.child(s)
		}
		n := newNode(d)
		switch last := segs[len(segs)-1]; last {
		case "*":
			cur.star = n
		case "[]":
			cur.items = n
		default:
			cur.named[last] = n
		}
	}
	c := compiler{ix}
	out := c.object(root)
	out["$schema"] = Dialect
	out["title"] = ix.Path
	out["$comment"] = "Generated by `pipeline schema` from " + ix.Path + ". Each attribute's x-rule names the rule it is declared under; change the `- key` lines there, never this output (DESIGN §4)."
	if len(shapes) > 0 {
		defs := map[string]any{}
		for name, n := range shapes {
			defs[strings.TrimPrefix(name, "$")] = c.node(n)
		}
		out["$defs"] = defs
	}
	return out, nil
}

func (n *node) child(seg string) *node {
	switch seg {
	case "*":
		return n.star
	case "[]":
		return n.items
	}
	return n.named[seg]
}

type compiler struct{ ix reasons.Index }

// node is one declared attribute: each alternative of its type as an
// arm, quoted values gathered into one enum, and the annotations on the
// whole rather than on an arm.
func (c compiler) node(n *node) map[string]any {
	var arms []map[string]any
	var enum []any
	for _, t := range n.decl.Types {
		switch {
		case strings.HasPrefix(t, `"`):
			enum = append(enum, strings.Trim(t, `"`))
		case strings.HasPrefix(t, "$"):
			arms = append(arms, map[string]any{"$ref": "#/$defs/" + strings.TrimPrefix(t, "$")})
		case t == "map":
			arms = append(arms, c.object(n))
		case t == "list":
			a := map[string]any{"type": "array"}
			if n.items != nil {
				a["items"] = c.node(n.items)
			}
			arms = append(arms, a)
		case t == "any":
			arms = append(arms, map[string]any{})
		default:
			arms = append(arms, map[string]any{"type": t})
		}
	}
	if len(enum) > 0 {
		arms = append(arms, map[string]any{"enum": enum})
	}
	s := map[string]any{"anyOf": arms}
	if len(arms) == 1 {
		s = arms[0]
	}
	s["x-rule"] = c.ix.Name + "#" + n.decl.RuleID
	if r, ok := c.ix.Rule(n.decl.RuleID); ok && r.Text != "" {
		s["description"] = r.Text
	}
	return s
}

// object is a map: its ungated members as properties, each distinct
// `when` condition as one if/then, and closed unless it declares `*`.
func (c compiler) object(n *node) map[string]any {
	o := map[string]any{"type": "object"}
	if len(n.named) == 0 && n.star == nil {
		return o
	}
	type gate struct {
		key      string
		vals     []string
		props    map[string]any
		required []string
	}
	props := map[string]any{}
	var required []string
	gates := map[string]*gate{}
	var names []string
	for name := range n.named {
		names = append(names, name)
	}
	sort.Strings(names)
	for _, name := range names {
		child := n.named[name]
		d := child.decl
		if d.When == "" {
			props[name] = c.node(child)
			if d.Presence == "required" {
				required = append(required, name)
			}
			continue
		}
		vals := append([]string(nil), d.WhenIs...)
		sort.Strings(vals)
		k := d.When + "\x00" + strings.Join(vals, "\x00")
		g, ok := gates[k]
		if !ok {
			g = &gate{key: d.When, vals: vals, props: map[string]any{}}
			gates[k] = g
		}
		g.props[name] = c.node(child)
		if d.Presence == "required" {
			g.required = append(g.required, name)
		}
	}
	if len(props) > 0 {
		o["properties"] = props
	}
	if len(required) > 0 {
		o["required"] = required
	}
	if len(gates) > 0 {
		var keys []string
		for k := range gates {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		var all []any
		for _, k := range keys {
			g := gates[k]
			var vals []any
			for _, v := range g.vals {
				vals = append(vals, v)
			}
			then := map[string]any{"properties": g.props}
			if len(g.required) > 0 {
				then["required"] = g.required
			}
			all = append(all, map[string]any{
				"if":   map[string]any{"properties": map[string]any{g.key: map[string]any{"enum": vals}}, "required": []string{g.key}},
				"then": then,
			})
		}
		o["allOf"] = all
	}
	if n.star != nil {
		o["additionalProperties"] = c.node(n.star)
	} else {
		o["unevaluatedProperties"] = false
	}
	return o
}

// Marshal renders a compiled schema the way `pipeline schema` prints it:
// two-space indent, keys sorted (encoding/json sorts map keys, which is
// what makes the output byte-stable across runs), and `<` and `>` left
// as written, since rule leads carry placeholders like `<tier>`.
func Marshal(s map[string]any) ([]byte, error) {
	var b bytes.Buffer
	enc := json.NewEncoder(&b)
	enc.SetEscapeHTML(false)
	enc.SetIndent("", "  ")
	if err := enc.Encode(s); err != nil {
		return nil, err
	}
	return b.Bytes(), nil
}
